### ISSUE TITLE
Combine Efforts?

### ISSUE THREAD

**Issue by xjamundx** [mping/5to6#2]
I noticed there are a few similar projects:
https://github.com/5to6/5to6
https://github.com/thomasloh/5to6/issues/1

Any interest in combining efforts?

I think we all have the same goal basically...

**Comment by mping** [comment]
Sure, I'm all for combining efforts. I'm using `jstransform` which should be superseded by `recast`, your proj uses `estraverse`while @thomasloh uses `recast`, I'm not familiar with either so any one is good.

I'm tracking thomasloh/5to6#1 so if he is in, I'll close this.

**Comment by mping** [comment]
@xjamundx I didn't get from the issue if @thomasloh is interested in merging or not - he closed the issue.

**Comment by thomasloh** [comment]
@xjamundx @mping  I'm down for merging, what's the game plan?

**Comment by mping** [comment]
@thomasloh repo has more converters (me and @xjamundx only have one conversion AFAIK) so looking at that it would be easier just to migrate our own stuff onto @thomasloh repo than migrate all of his code to our style.

I'm cool with either, I just don't recommend mine because jstransform should be superseded anyway.
Later we can figure out the publish to npm stuff.

**Comment by xjamundx** [comment]
Yeah I wasn't sure either :) Glad to hear everyone wants to team. Let me give you all access to the 5to6 org! Here's how in my head it should work.
- You have a folder of transforms.
- You can enable or disable them.
- We parse the AST once, run it through X transforms (serially), then regenerate the output
- Generally we should use something like recast to make the output readable

My thing started as a twitter convo and ended up with this ideas repo here:
https://github.com/5to6/ideas/issues

A couple of days ago I started banging things out and went to publish and found it was already out there, so I was hoping we could combine our efforts a bit.

Let's move our discussions into issues over here?
https://github.com/5to6/5to6/issues

**Comment by thomasloh** [comment]
sorry could have been clearer  =) but yeah I agree with the above workflow ^

**Comment by mping** [comment]
ok let's move then.

**Comment by xjamundx** [comment]
Great. By all means be owners of the combined project. I'm sure none of us has a lot of time to work on this, so go ahead and move forward. We can establish ground rules as we go :)

The thing I care about the most if a simple interface for end users in the form of a CLI (and corresponding API)
